version: '2.1'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "./wait-for-it.sh db:5432 && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
