# Generated by Django 2.0.5 on 2018-05-15 19:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiftEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lift_type', models.CharField(choices=[('BP', 'Bench Press'), ('SQ', 'Squat'), ('OHP', 'Overhead Press'), ('DL', 'Deadlift')], max_length=3)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('rpe', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10')], max_length=3)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_workout', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='liftentry',
            name='workout_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift.WorkoutSession'),
        ),
    ]
